config_version = 14

[accessibility]
ui_scale = 1.2000000104308128

[audio]
enable_sounds = true

[backdrop]
enabled = true

[bar]
order = [ "default" ]

    [bar.default]
    capsule = true
    capsule_padding = 7.0
    capsule_thickness = 0.76999998651444912
    center = [ "clock", "workspaces", "cat" ]
    end = [ "widget", "ram", "temp", "battery", "network", "notifications", "tray" ]
    font_scale = 1.0999999828636646
    margin_ends = 0
    radius_top_left = 0
    radius_top_right = 0
    scale = 1.1000000089406967
    start = [ "media" ]
    thickness = 40

[battery]
warning_threshold = 25

[brightness]
enable_ddcutil = true
minimum_brightness = 0.0099999997764825821

[[control_center.shortcuts]]
type = "wifi"

[[control_center.shortcuts]]
type = "nightlight"

[[control_center.shortcuts]]
type = "notification"

[[control_center.shortcuts]]
type = "dark_mode"

[[control_center.shortcuts]]
type = "session"

[desktop_widgets]
schema_version = 2
widget_order = [ "desktop-widget-0000000000000001", "desktop-widget-0000000000000002" ]

    [desktop_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [desktop_widgets.widget.desktop-widget-0000000000000001]
    box_height = 368.0
    box_width = 1920.0
    cx = 960.0
    cy = 1016.0
    output = "eDP-1"
    placement_height = 1200.0
    placement_width = 1920.0
    rotation = 0.0
    type = "audio_visualizer"

        [desktop_widgets.widget.desktop-widget-0000000000000001.settings]
        background = false
        bands = 128
        centered = false
        color_1 = "primary"
        mirrored = false
        reversed = false
        show_when_idle = true

    [desktop_widgets.widget.desktop-widget-0000000000000002]
    box_height = 128.0
    box_width = 320.0
    cx = 208.0
    cy = 168.0
    output = "eDP-1"
    placement_height = 1200.0
    placement_width = 1920.0
    rotation = 0.0
    type = "clock"

        [desktop_widgets.widget.desktop-widget-0000000000000002.settings]
        format = "{:%A\\n %I:%M %p}"

[location]
auto_locate = true

[lockscreen]
blurred_desktop = true

[lockscreen_widgets]
enabled = true
schema_version = 2
widget_order = [
    "lockscreen-login-box@HDMI-A-1",
    "lockscreen-login-box@WL-1",
    "lockscreen-login-box@winit",
    "lockscreen-login-box@eDP-1",
    "lockscreen-widget-0000000000000001",
    "lockscreen-widget-0000000000000002"
]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1"]
    box_height = 196.0
    box_width = 810.0
    cx = 960.0
    cy = 898.0
    output = "HDMI-A-1"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

    [lockscreen_widgets.widget."lockscreen-login-box@WL-1"]
    box_height = 196.0
    box_width = 810.0
    cx = 473.0
    cy = 960.0
    output = "WL-1"
    placement_height = 1142.0
    placement_width = 946.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@WL-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

    [lockscreen_widgets.widget."lockscreen-login-box@eDP-1"]
    box_height = 196.0
    box_width = 848.0
    cx = 930.0
    cy = 1030.0
    output = "eDP-1"
    placement_height = 1200.0
    placement_width = 1920.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@eDP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 16.0
        center_password_text = true
        input_opacity = 1.0
        input_radius = 12.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = false

    [lockscreen_widgets.widget."lockscreen-login-box@winit"]
    box_height = 196.0
    box_width = 810.0
    cx = 473.0
    cy = 960.0
    output = "winit"
    placement_height = 1142.0
    placement_width = 946.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@winit".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000001]
    box_height = 0.0
    box_width = 0.0
    cx = 960.0
    cy = 600.0
    output = "eDP-1"
    placement_height = 1200.0
    placement_width = 1920.0
    rotation = 0.0
    type = "clock"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000001.settings]
        background = true
        clock_style = "digital"
        format = "{:%I:%M %p}"

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000002]
    box_height = 112.0
    box_width = 208.0
    cx = 960.0
    cy = 424.0
    output = "eDP-1"
    placement_height = 1200.0
    placement_width = 1920.0
    rotation = 0.0
    type = "weather"

[nightlight]
enabled = true
force = true

[osd]
scale = 1.1000000089406967

[plugin_settings."noctalia/wallpaper_depth"]
manager_open_near_click = true

[plugins]
auto_update = "all"
enabled = [ "noctalia/notes", "dotnetrob/cat", "thepunkoff/pomodoro" ]

    [[plugins.source]]
    kind = "git"
    location = "https://github.com/noctalia-dev/official-plugins"
    name = "official"

    [[plugins.source]]
    kind = "git"
    location = "https://github.com/noctalia-dev/community-plugins"
    name = "community"

[shell]
password_style = "random"
polkit_agent = true
screen_time_enabled = true
telemetry_enabled = true

    [shell.greeter_sync]
    privilege_command = "foot pkexec"

    [shell.panel]
    control_center_position = "center"
    open_near_click_control_center = true
    wallpaper_placement = "floating"
    wallpaper_position = "bottom_center"

    [shell.screen_corners]
    enabled = true

[theme]
builtin = "Rosé Pine"
mode = "dark"
pure_black_dark = true
source = "wallpaper"
wallpaper_scheme = "m3-content"

    [theme.templates]
    builtin_ids = [ "gtk3", "gtk4", "niri", "qt" ]

[wallpaper]
directory = "~/Pictures/Wallpapers"
transition = [ "honeycomb", "stripes" ]
transition_on_startup = true

    [wallpaper.default]
    path = "~/Pictures/Wallpapers/wallhaven-qrow67.png"

    [wallpaper.last]
    path = "~/Pictures/Wallpapers/wallhaven-qrow67.png"

    [wallpaper.monitors.eDP-1]
    path = "~/Pictures/Wallpapers/wallhaven-qrow67.png"

    [[wallpaper.favorite]]
    path = "~/Pictures/Wallpapers/wallhaven-qrow67.png"
    theme_mode = "auto"

[widget.cat]
type = "dotnetrob/cat:cat"

[widget.clock]
format = "{:%I:%M %p}"

[widget.media]
color = "primary"
hide_when_no_media = true
show_progress = true

[widget.network]
show_label = false

[widget.ram]
visualization = "none"

[widget.temp]
visualization = "none"

[widget.widget]
type = "thepunkoff/pomodoro:widget"

[widget.workspaces]
hide_when_empty = true
show_labels = false